#!/usr/bin/env bash
#add a custom Nginx response header
web1='\\tadd_header X-Served-By $HOSTNAME;'
sudo chown -R "$USER":"$USER" /etc/nginx
sed -i "13i $web1" /etc/nginx/nginx.conf
sudo service nginx restart
